// <auto-generated />
using System;
using CompanyInvoiceSystem.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CompanyInvoiceSystem.WebApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20201009042232_UseMigrationConfig")]
    partial class UseMigrationConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CompanyInvoiceSystem.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EIN")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDomestic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("INDEX_Companies__Company_NAME");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae860ae3-9120-4b12-9cc1-a6e1396814ef"),
                            EIN = 123456789,
                            Name = "AZ Tech"
                        },
                        new
                        {
                            Id = new Guid("2ea2b7af-6fbc-4f56-a275-c124b7acf7c9"),
                            EIN = 100000001,
                            Name = "Brooklyn Trucks Inc."
                        },
                        new
                        {
                            Id = new Guid("d99f9213-ddb9-4ea2-bcc6-3e411a78d9bd"),
                            EIN = 100000331,
                            Name = "Alt Solutions"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
